baseurl: /
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
paginate_path: "page:num"
permalink: /:categories/:year/:month/:title
highlighter: pygments
paginate: 5